sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: LTAI5tGbvBTMFWG5bnRwcu9n
      access-key-secret: KqYovudQoXtmCWAmrdcmVqUnvPKYHC
      bucket-name: web-jyc
  redis:
    host: localhost
    port: 6379
    database: 10
    timeout: 5000